import type { Metadata } from "next";
import { GeistSans } from "geist/font/sans";
import clsx from "clsx";
import "./globals.css";

export const metadata: Metadata = {
	title: "Swift",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body
				className={clsx(
					GeistSans.className,
					"py-8 px-6 lg:p-10 bg-white min-h-dvh flex items-center justify-center"
				)}
			>
				{children}
			</body>
		</html>
	);
}
